# -*- coding: utf-8 -*-
"""greetingapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tLrSATHLmOKvbXQSZmJZ1Y9O5KjoOjsK
"""

import streamlit as st
st.title("👋 مرحبا بكم في موقعنا الأول باستخدام ستريم ليت")
name = st.text_input("👋 ما هو اسمك؟")
if name:
    st.write("نورت الموقع، مرحبا بك يا", name)
    st.balloons()